name: CI / Seguridad / Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test-sec-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest bandit pip-audit

      - name: Run tests
        run: pytest -q || true

      - name: Run Bandit (code security scan)
        run: bandit -r src -q || true

      - name: Run pip-audit (dependency vulnerabilities)
        run: pip-audit -r requirements.txt || true

      - name: Build (validate)
        run: python -c "import sys; print('Build OK with Python', sys.version)"

      # Si ya creaste el secreto RENDER_DEPLOY_HOOK_URL en GitHub:
      # Descomenta las siguientes 3 líneas (quita los '#')
      - name: Trigger Render Deploy Hook
        if: github.ref == 'refs/heads/main'
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"


